
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useMemo } from 'react';

// Custom-made fallback placeholders for Chat mode
const CHAT_FALLBACK_PLACEHOLDERS = [
  'Ask me anything...',
  'Tell me a fun fact about the Roman Empire',
  'What is the weather like in Tokyo right now?',
  'Explain quantum computing in simple terms',
  'Write a short poem about a rainy day',
  'Who was the first person to walk on the moon?',
  'Translate "Hello, world!" to Spanish',
  'Give me a recipe for chocolate chip cookies',
  'Summarize the plot of "Hamlet"',
  'What are the main causes of climate change?',
  'Help me brainstorm ideas for a birthday gift',
  "What's the capital of Australia?",
  'How does photosynthesis work?',
  'Draft an email to my boss asking for a raise',
  'Tell me a joke',
  'What are some good books to read this month?',
  "Explain the theory of relativity like I'm five",
  'Help me plan a weekend trip to a nearby city',
  'What are the health benefits of green tea?',
  'Write a haiku about the ocean',
  'Compare and contrast cats and dogs',
  'What was the significance of the Silk Road?',
  'Help me practice for a job interview',
  'What are some tips for learning a new language?',
  'Create a travel itinerary for a week in Italy',
  "What's the difference between a virus and a bacteria?",
  'Write a short story about a detective in the future',
  'How do I tie a tie?',
  'Give me some workout ideas I can do at home',
  'Explain the stock market',
  'What are the seven wonders of the ancient world?',
  'What are some interesting historical facts?',
  "What's a good movie to watch tonight?",
  'Tell me about the history of the internet',
  'How can I be more productive?',
  'Write a song about a robot who falls in love',
  'What are the planets in our solar system?',
  'Help me write a thank you note',
  'Explain the concept of black holes',
  'What are some famous philosophical questions?',
  'Tell me about the life of Leonardo da Vinci',
  'How to make a perfect cup of coffee',
  'What are the main branches of philosophy?',
  'Write a dialogue between a cat and a dog',
  "What's the population of Earth?",
  'Help me come up with a name for my new puppy',
  'How does a car engine work?',
  'What are some mindfulness exercises?',
  'Tell me an interesting fact about animals',
  'What is the Pythagorean theorem?',
  'Help me create a weekly meal plan',
  'Explain the difference between AI, ML, and DL',
  'Write a review for a fictional restaurant',
  'What are the rules of chess?',
  'Tell me about the history of photography',
  'How can I improve my public speaking skills?',
  'What are the primary colors?',
  'Write a letter to my future self',
  'What are the key events of World War II?',
  'Help me understand a complex scientific paper',
  'What are some common logical fallacies?',
  'Tell me a story in the style of Edgar Allan Poe',
  'How is glass made?',
  "What's the best way to learn guitar?",
  'Explain the water cycle',
  'Write a tagline for a new tech startup',
  'What is DNA and what does it do?',
  'Help me plan a D&D campaign',
  'What are the main principles of design?',
  'Tell me about a famous artist',
  'How do electric cars work?',
  'What are some tips for better sleep?',
  'Write a sonnet about the beauty of nature',
  'What is the difference between weather and climate?',
  'Help me come up with a business idea',
  'Explain what blockchain is',
  'What are some interesting historical myths?',
  'Write a movie pitch',
  'How do I start a garden?',
  'What are the different types of clouds?',
  'Tell me about the architecture of ancient Rome',
  'What are the key features of a healthy diet?',
  'Write a monologue from the perspective of a villain',
  'How does the judicial system work?',
  'What are some good podcasts to listen to?',
  'Explain the concept of supply and demand',
  'Tell me about a famous scientific discovery',
  'How can I build a good credit score?',
  'Write a description of a fantasy world',
  'What is the history of the Olympic Games?',
  'Help me learn basic conversational phrases in Japanese',
  'Explain the process of making cheese',
  'What are the major world religions?',
  'Write a social media post for a new product launch',
  "What are the layers of the Earth's atmosphere?",
  'Tell me about a creature from mythology',
  'How can I write a compelling story?',
  "What are the duties of a country's president?",
  'Write an acceptance speech for a fictional award',
  'How does a 3D printer work?',
];

/**
 * A custom hook to manage a dynamic placeholder for an input field.
 * Returns a shuffled list of placeholders appropriate for the current mode.
 * The consuming component (MessageForm) uses this list to render the typing effect.
 */
export const usePlaceholder = (isEnabled: boolean, conversationContext: string, isAgentMode: boolean, hasApiKey: boolean) => {
    return useMemo(() => {
        const list = CHAT_FALLBACK_PLACEHOLDERS;
        return [...list].sort(() => 0.5 - Math.random());
    }, [isAgentMode]);
};
