/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { FunctionDeclaration, Type } from "@google/genai";
import { ToolError } from '../types';
import { executePythonWithPyodide } from './codeExecutor/pythonExecutor';
import { executeJsInWorker } from './codeExecutor/jsExecutor';
import { executeWithPiston } from './codeExecutor/pistonExecutor';
import { fileStore } from '../services/fileStore';

export const codeExecutorDeclaration: FunctionDeclaration = {
  name: 'executeCode',
  description: 'Executes code in a secure sandboxed environment. Supports Python, JavaScript, and other languages. For Python, it can install packages from PyPI, perform network requests, and read user-provided files.',
  parameters: {
    type: Type.OBJECT,
    properties: {
      language: {
        type: Type.STRING,
        description: 'The programming language of the code to execute.'
      },
      code: {
        type: Type.STRING,
        description: 'The code snippet to execute.'
      },
      packages: {
        type: Type.ARRAY,
        description: '(Python only) A list of PyPI packages to install before running the code (e.g., ["numpy", "pandas", "requests"]).',
        items: { type: Type.STRING }
      },
      cdn_urls: {
        type: Type.ARRAY,
        description: '(JavaScript only) A list of CDN URLs for external libraries to import before running the code.',
        items: { type: Type.STRING }
      },
      input_filenames: {
        type: Type.ARRAY,
        description: '(Python only) A list of filenames from the virtual filesystem (e.g., user-attached files, or files generated by other tools like `/main/output/image.png`). The tool will load these files into the `/main/input/` directory for the script to use.',
        items: { type: Type.STRING }
      }
    },
    required: ['language', 'code'],
  },
};

// --- Main Dispatcher ---
export const executeCode = async (args: { language: string; code: string; packages?: string[]; cdn_urls?: string[]; input_filenames?: string[] }): Promise<string> => {
  const { language, code, packages, cdn_urls, input_filenames } = args;
  const lang = language.toLowerCase();

  try {
    if (lang === 'python' || lang === 'py') {
        const input_files_data = [];
        let notFoundFiles: string[] = [];
        if (input_filenames && input_filenames.length > 0) {
            for (const path of input_filenames) {
                const blob = await fileStore.getFile(path);
                if (blob) {
                    const data = new Uint8Array(await blob.arrayBuffer());
                    const filename = path.split('/').pop() || path;
                    input_files_data.push({ filename, data });
                } else {
                    notFoundFiles.push(path);
                }
            }
        }
        if (notFoundFiles.length > 0) {
            throw new ToolError('executeCode', 'FILE_NOT_FOUND', `The following input files were not found in the virtual filesystem: ${notFoundFiles.join(', ')}`, undefined, "One or more files needed for this code could not be found. Try using the `listFiles` tool to see available files.");
        }
        return await executePythonWithPyodide(code, packages, input_files_data);
    }

    if (lang === 'javascript' || lang === 'js' || lang === 'html') {
      return await executeJsInWorker(code, cdn_urls);
    }
    
    return await executeWithPiston(lang, code);
  } catch (error) {
    const originalError = error instanceof Error ? error : new Error(String(error));
    if (error instanceof ToolError) throw error; // Re-throw tool errors
    throw new ToolError('executeCode', 'EXECUTION_FAILED', originalError.message, originalError, "An error occurred while executing the code. Check the 'Details' for technical information and try correcting the code.");
  }
};