/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { FunctionDeclaration, Type, GoogleGenAI } from "@google/genai";
import { ToolError } from '../types';
import { getText } from '../utils/geminiUtils';
// FIX: Fix module import path for `parseApiError` to point to the barrel file, resolving ambiguity with an empty `gemini.ts` file.
import { parseApiError } from '../services/gemini/index';
import { fileStore } from '../services/fileStore';
import { fileToBase64 } from '../utils/fileUtils';

export const displayMapDeclaration: FunctionDeclaration = {
  name: 'displayMap',
  description: 'Displays an interactive map centered on a specific geographical location.',
  parameters: {
    type: Type.OBJECT,
    properties: {
      latitude: { type: Type.NUMBER, description: 'The latitude for the center of the map.' },
      longitude: { type: Type.NUMBER, description: 'The longitude for the center of the map.' },
      zoom: { type: Type.NUMBER, description: 'The zoom level of the map, from 1 (world) to 18 (street level). Default is 13.' },
      markerText: { type: Type.STRING, description: 'Optional text to display in a popup on a marker at the specified location.' }
    },
    required: ['latitude', 'longitude'],
  },
};

export const executeDisplayMap = (args: { latitude: number; longitude: number; zoom?: number, markerText?: string }): string => {
  const { latitude, longitude, zoom = 13, markerText } = args;

  if (typeof latitude !== 'number' || typeof longitude !== 'number') {
      throw new ToolError('displayMap', 'INVALID_COORDINATES', 'Latitude and longitude must be numbers.');
  }

  const mapData = {
      latitude,
      longitude,
      zoom,
      markerText
  };

  return `[MAP_COMPONENT]${JSON.stringify(mapData)}[/MAP_COMPONENT]`;
};

export const analyzeMapVisuallyDeclaration: FunctionDeclaration = {
  name: 'analyzeMapVisually',
  description: 'Analyzes the map area at a given latitude and longitude and returns a textual description of visible landmarks, parks, and road layouts. Use this after displaying a map if you need to "see" what is on it.',
  parameters: {
    type: Type.OBJECT,
    properties: {
      latitude: { type: Type.NUMBER, description: 'The latitude of the map area to analyze.' },
      longitude: { type: Type.NUMBER, description: 'The longitude of the map area to analyze.' },
    },
    required: ['latitude', 'longitude'],
  },
};

export const executeAnalyzeMapVisually = async (args: { latitude: number, longitude: number }): Promise<string> => {
  const { latitude, longitude } = args;
  if (typeof latitude !== 'number' || typeof longitude !== 'number') {
    throw new ToolError('analyzeMapVisually', 'INVALID_COORDINATES', 'Latitude and longitude must be numbers.');
  }

  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });
    const prompt = `
      You are a cartography expert.
      Based on the geographical coordinates latitude=${latitude} and longitude=${longitude}, provide a concise, bulleted list describing the key landmarks, major roads, parks, and general layout of the immediate area.
      Focus on what would be visually prominent on a standard map view.
      Do not mention the coordinates in your response.
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    
    const description = getText(response);
    return `Visual analysis of the map at lat ${latitude.toFixed(4)}, lon ${longitude.toFixed(4)}:\n${description}`;

  } catch (err) {
    console.error("Visual map analysis tool failed:", err);
    const errorMessage = err instanceof Error ? err.message : "An unknown error occurred during map analysis.";
    throw new ToolError('analyzeMapVisually', 'ANALYSIS_FAILED', errorMessage, err as Error);
  }
};

export const analyzeImageVisuallyDeclaration: FunctionDeclaration = {
  name: 'analyzeImageVisually',
  description: 'Analyzes a visual image and returns a detailed textual description. Use this to "see" and validate the content of images generated by `generateImage` or screenshots from `captureCodeOutputScreenshot`.',
  parameters: {
    type: Type.OBJECT,
    properties: {
      filePath: { type: Type.STRING, description: 'The full path of the image file in the virtual filesystem to analyze (e.g., "/main/output/image-xyz.png").' },
      imageBase64: { type: Type.STRING, description: 'A base64 encoded string of an image to analyze. Typically used with the output from `captureCodeOutputScreenshot`.' },
    },
  },
};

export const executeAnalyzeImageVisually = async (args: { filePath?: string, imageBase64?: string }): Promise<string> => {
  const { filePath, imageBase64 } = args;

  if (!filePath && !imageBase64) {
    throw new ToolError('analyzeImageVisually', 'MISSING_ARGUMENT', 'Either filePath or imageBase64 must be provided.');
  }

  let base64Data: string;
  let mimeType: string = 'image/png'; // Assume PNG if not specified

  try {
    if (filePath) {
      const blob = await fileStore.getFile(filePath);
      if (!blob) throw new Error(`File not found at path: ${filePath}`);
      mimeType = blob.type;
      // fileToBase64 already strips the prefix
      base64Data = await fileToBase64(new File([blob], filePath));
    } else {
      base64Data = imageBase64!;
    }

    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });
    const imagePart = { inlineData: { mimeType, data: base64Data } };
    const textPart = { text: "Describe this image in meticulous detail. What does it show? Are there any visible flaws, errors, or unexpected elements?" };
    
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-pro',
        contents: { parts: [imagePart, textPart] },
    });

    const description = getText(response);
    return `Visual analysis of the image:\n${description}`;

  } catch (err) {
    const originalError = err instanceof Error ? err : new Error(String(err));
    console.error("Image analysis tool failed:", originalError);
    throw new ToolError('analyzeImageVisually', 'ANALYSIS_FAILED', originalError.message, originalError);
  }
};